// Code generated by pgngen; DO NOT EDIT.

package pgn

// signExtend performs sign extension on a value with the given number of significant bits.
func signExtend(v uint64, bits int) int64 {
	shift := uint(64 - bits)
	return int64(v<<shift) >> shift
}

// decodeFixedStr extracts the ASCII string from a fixed-width field,
// terminating at the first null (0x00) or padding (0xFF) byte.
func decodeFixedStr(data []byte) string {
	for i, b := range data {
		if b == 0x00 || b == 0xFF {
			return string(data[:i])
		}
	}
	return string(data)
}

// encodeFixedStr writes s into a fixed-width field, padding with 0xFF.
func encodeFixedStr(dst []byte, s string) {
	n := copy(dst, s)
	for i := n; i < len(dst); i++ {
		dst[i] = 0xFF
	}
}
