// Code generated by pgngen; DO NOT EDIT.

package pgn

import (
	"encoding/binary"
	"fmt"
	"math"
)

// TemperatureSource is a lookup enumeration.
type TemperatureSource uint8

const (
	TemperatureSourceSea TemperatureSource = 0
	TemperatureSourceOutside TemperatureSource = 1
	TemperatureSourceInside TemperatureSource = 2
	TemperatureSourceEngineRoom TemperatureSource = 3
	TemperatureSourceMainCabin TemperatureSource = 4
	TemperatureSourceLiveWell TemperatureSource = 5
	TemperatureSourceBaitWell TemperatureSource = 6
	TemperatureSourceRefrigeration TemperatureSource = 7
	TemperatureSourceHeatingSystem TemperatureSource = 8
	TemperatureSourceDewPoint TemperatureSource = 9
	TemperatureSourceApparentWindChill TemperatureSource = 10
	TemperatureSourceTheoreticalWindChill TemperatureSource = 11
	TemperatureSourceHeatIndex TemperatureSource = 12
	TemperatureSourceFreezer TemperatureSource = 13
	TemperatureSourceExhaustGas TemperatureSource = 14
)

func (v TemperatureSource) String() string {
	switch v {
	case TemperatureSourceSea:
		return "sea"
	case TemperatureSourceOutside:
		return "outside"
	case TemperatureSourceInside:
		return "inside"
	case TemperatureSourceEngineRoom:
		return "engine_room"
	case TemperatureSourceMainCabin:
		return "main_cabin"
	case TemperatureSourceLiveWell:
		return "live_well"
	case TemperatureSourceBaitWell:
		return "bait_well"
	case TemperatureSourceRefrigeration:
		return "refrigeration"
	case TemperatureSourceHeatingSystem:
		return "heating_system"
	case TemperatureSourceDewPoint:
		return "dew_point"
	case TemperatureSourceApparentWindChill:
		return "apparent_wind_chill"
	case TemperatureSourceTheoreticalWindChill:
		return "theoretical_wind_chill"
	case TemperatureSourceHeatIndex:
		return "heat_index"
	case TemperatureSourceFreezer:
		return "freezer"
	case TemperatureSourceExhaustGas:
		return "exhaust_gas"
	default:
		return fmt.Sprintf("TemperatureSource(%d)", v)
	}
}

// HumiditySource is a lookup enumeration.
type HumiditySource uint8

const (
	HumiditySourceInside HumiditySource = 0
	HumiditySourceOutside HumiditySource = 1
)

func (v HumiditySource) String() string {
	switch v {
	case HumiditySourceInside:
		return "inside"
	case HumiditySourceOutside:
		return "outside"
	default:
		return fmt.Sprintf("HumiditySource(%d)", v)
	}
}

// PressureSource is a lookup enumeration.
type PressureSource uint8

const (
	PressureSourceAtmospheric PressureSource = 0
	PressureSourceWater PressureSource = 1
	PressureSourceSteam PressureSource = 2
	PressureSourceCompressedAir PressureSource = 3
	PressureSourceHydraulic PressureSource = 4
	PressureSourceFilter PressureSource = 5
	PressureSourceAltimeter PressureSource = 6
	PressureSourceOil PressureSource = 7
	PressureSourceFuel PressureSource = 8
)

func (v PressureSource) String() string {
	switch v {
	case PressureSourceAtmospheric:
		return "atmospheric"
	case PressureSourceWater:
		return "water"
	case PressureSourceSteam:
		return "steam"
	case PressureSourceCompressedAir:
		return "compressed_air"
	case PressureSourceHydraulic:
		return "hydraulic"
	case PressureSourceFilter:
		return "filter"
	case PressureSourceAltimeter:
		return "altimeter"
	case PressureSourceOil:
		return "oil"
	case PressureSourceFuel:
		return "fuel"
	default:
		return fmt.Sprintf("PressureSource(%d)", v)
	}
}

// HeadingReference is a lookup enumeration.
type HeadingReference uint8

const (
	HeadingReferenceTrue HeadingReference = 0
	HeadingReferenceMagnetic HeadingReference = 1
)

func (v HeadingReference) String() string {
	switch v {
	case HeadingReferenceTrue:
		return "true"
	case HeadingReferenceMagnetic:
		return "magnetic"
	default:
		return fmt.Sprintf("HeadingReference(%d)", v)
	}
}

// SpeedType is a lookup enumeration.
type SpeedType uint8

const (
	SpeedTypePaddleWheel SpeedType = 0
	SpeedTypePitotTube SpeedType = 1
	SpeedTypeDoppler SpeedType = 2
	SpeedTypeCorrelation SpeedType = 3
	SpeedTypeElectromagnetic SpeedType = 4
)

func (v SpeedType) String() string {
	switch v {
	case SpeedTypePaddleWheel:
		return "paddle_wheel"
	case SpeedTypePitotTube:
		return "pitot_tube"
	case SpeedTypeDoppler:
		return "doppler"
	case SpeedTypeCorrelation:
		return "correlation"
	case SpeedTypeElectromagnetic:
		return "electromagnetic"
	default:
		return fmt.Sprintf("SpeedType(%d)", v)
	}
}

// WindReference is a lookup enumeration.
type WindReference uint8

const (
	WindReferenceTrueNorth WindReference = 0
	WindReferenceMagneticNorth WindReference = 1
	WindReferenceApparent WindReference = 2
	WindReferenceTrueBoat WindReference = 3
	WindReferenceTrueWater WindReference = 4
)

func (v WindReference) String() string {
	switch v {
	case WindReferenceTrueNorth:
		return "true_north"
	case WindReferenceMagneticNorth:
		return "magnetic_north"
	case WindReferenceApparent:
		return "apparent"
	case WindReferenceTrueBoat:
		return "true_boat"
	case WindReferenceTrueWater:
		return "true_water"
	default:
		return fmt.Sprintf("WindReference(%d)", v)
	}
}

// DirectionReference is a lookup enumeration.
type DirectionReference uint8

const (
	DirectionReferenceTrue DirectionReference = 0
	DirectionReferenceMagnetic DirectionReference = 1
	DirectionReferenceError DirectionReference = 2
	DirectionReferenceNull DirectionReference = 3
)

func (v DirectionReference) String() string {
	switch v {
	case DirectionReferenceTrue:
		return "true"
	case DirectionReferenceMagnetic:
		return "magnetic"
	case DirectionReferenceError:
		return "error"
	case DirectionReferenceNull:
		return "null"
	default:
		return fmt.Sprintf("DirectionReference(%d)", v)
	}
}

// EngineParametersRapidUpdate represents PGN 127488 — Engine Parameters Rapid Update.
type EngineParametersRapidUpdate struct {
	EngineInstance uint8 `json:"engine_instance"`
	EngineSpeed float64 `json:"engine_speed"` // rpm
	EngineBoost float64 `json:"engine_boost"` // Pa
	EngineTiltTrim int8 `json:"engine_tilt_trim"`
}

func (EngineParametersRapidUpdate) PGN() uint32 { return 127488 }

// DecodeEngineParametersRapidUpdate decodes PGN 127488 from raw bytes.
func DecodeEngineParametersRapidUpdate(data []byte) (EngineParametersRapidUpdate, error) {
	if len(data) < 8 {
		return EngineParametersRapidUpdate{}, fmt.Errorf("pgn 127488: need 8 bytes, got %d", len(data))
	}
	var m EngineParametersRapidUpdate
	m.EngineInstance = data[0]
	m.EngineSpeed = float64(binary.LittleEndian.Uint16(data[1:3])) * 0.25
	m.EngineBoost = float64(binary.LittleEndian.Uint16(data[3:5])) * 100.0
	m.EngineTiltTrim = int8(data[5])
	return m, nil
}

// Encode serializes EngineParametersRapidUpdate to raw bytes.
func (m *EngineParametersRapidUpdate) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.EngineInstance))
	binary.LittleEndian.PutUint16(data[1:3], uint16(uint64(math.Round(m.EngineSpeed / 0.25))))
	binary.LittleEndian.PutUint16(data[3:5], uint16(uint64(math.Round(m.EngineBoost / 100.0))))
	data[5] = byte(uint64(m.EngineTiltTrim))
	return data
}

// EngineParametersDynamic represents PGN 127489 — Engine Parameters Dynamic.
type EngineParametersDynamic struct {
	EngineInstance uint8 `json:"engine_instance"`
	OilPressure float64 `json:"oil_pressure"` // Pa
	OilTemperature float64 `json:"oil_temperature"` // K
	Temperature float64 `json:"temperature"` // K
	AlternatorPotential float64 `json:"alternator_potential"` // V
	FuelRate float64 `json:"fuel_rate"` // L/h
	TotalEngineHours float64 `json:"total_engine_hours"` // s
	CoolantPressure float64 `json:"coolant_pressure"` // Pa
	FuelPressure float64 `json:"fuel_pressure"` // Pa
	DiscreteStatus1 uint16 `json:"discrete_status_1"`
	DiscreteStatus2 uint16 `json:"discrete_status_2"`
	PercentEngineLoad int8 `json:"percent_engine_load"` // %
	PercentEngineTorque int8 `json:"percent_engine_torque"` // %
}

func (EngineParametersDynamic) PGN() uint32 { return 127489 }

// DecodeEngineParametersDynamic decodes PGN 127489 from raw bytes.
func DecodeEngineParametersDynamic(data []byte) (EngineParametersDynamic, error) {
	if len(data) < 26 {
		return EngineParametersDynamic{}, fmt.Errorf("pgn 127489: need 26 bytes, got %d", len(data))
	}
	var m EngineParametersDynamic
	m.EngineInstance = data[0]
	m.OilPressure = float64(binary.LittleEndian.Uint16(data[1:3])) * 100.0
	m.OilTemperature = float64(binary.LittleEndian.Uint16(data[3:5])) * 0.1
	m.Temperature = float64(binary.LittleEndian.Uint16(data[5:7])) * 0.01
	m.AlternatorPotential = float64(int16(binary.LittleEndian.Uint16(data[7:9]))) * 0.01
	m.FuelRate = float64(int16(binary.LittleEndian.Uint16(data[9:11]))) * 0.1
	m.TotalEngineHours = float64(binary.LittleEndian.Uint32(data[11:15])) * 1.0
	m.CoolantPressure = float64(binary.LittleEndian.Uint16(data[15:17])) * 100.0
	m.FuelPressure = float64(binary.LittleEndian.Uint16(data[17:19])) * 1000.0
	m.DiscreteStatus1 = binary.LittleEndian.Uint16(data[20:22])
	m.DiscreteStatus2 = binary.LittleEndian.Uint16(data[22:24])
	m.PercentEngineLoad = int8(data[24])
	m.PercentEngineTorque = int8(data[25])
	return m, nil
}

// Encode serializes EngineParametersDynamic to raw bytes.
func (m *EngineParametersDynamic) Encode() []byte {
	data := make([]byte, 26)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.EngineInstance))
	binary.LittleEndian.PutUint16(data[1:3], uint16(uint64(math.Round(m.OilPressure / 100.0))))
	binary.LittleEndian.PutUint16(data[3:5], uint16(uint64(math.Round(m.OilTemperature / 0.1))))
	binary.LittleEndian.PutUint16(data[5:7], uint16(uint64(math.Round(m.Temperature / 0.01))))
	binary.LittleEndian.PutUint16(data[7:9], uint16(uint64(int64(math.Round(m.AlternatorPotential / 0.01)))))
	binary.LittleEndian.PutUint16(data[9:11], uint16(uint64(int64(math.Round(m.FuelRate / 0.1)))))
	binary.LittleEndian.PutUint32(data[11:15], uint32(uint64(math.Round(m.TotalEngineHours / 1.0))))
	binary.LittleEndian.PutUint16(data[15:17], uint16(uint64(math.Round(m.CoolantPressure / 100.0))))
	binary.LittleEndian.PutUint16(data[17:19], uint16(uint64(math.Round(m.FuelPressure / 1000.0))))
	binary.LittleEndian.PutUint16(data[20:22], uint16(uint64(m.DiscreteStatus1)))
	binary.LittleEndian.PutUint16(data[22:24], uint16(uint64(m.DiscreteStatus2)))
	data[24] = byte(uint64(m.PercentEngineLoad))
	data[25] = byte(uint64(m.PercentEngineTorque))
	return data
}

// FluidLevel represents PGN 127505 — Fluid Level.
type FluidLevel struct {
	Instance uint8 `json:"instance"`
	FluidType uint8 `json:"fluid_type"`
	Level float64 `json:"level"` // %
	Capacity float64 `json:"capacity"` // L
}

func (FluidLevel) PGN() uint32 { return 127505 }

// DecodeFluidLevel decodes PGN 127505 from raw bytes.
func DecodeFluidLevel(data []byte) (FluidLevel, error) {
	if len(data) < 8 {
		return FluidLevel{}, fmt.Errorf("pgn 127505: need 8 bytes, got %d", len(data))
	}
	var m FluidLevel
	m.Instance = data[0] & 0x0F
	m.FluidType = (data[0] >> 4) & 0x0F
	m.Level = float64(int16(binary.LittleEndian.Uint16(data[1:3]))) * 0.004
	m.Capacity = float64(binary.LittleEndian.Uint32(data[3:7])) * 0.1
	return m, nil
}

// Encode serializes FluidLevel to raw bytes.
func (m *FluidLevel) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = (data[0] & ^byte(0x0F << 0)) | byte((uint64(m.Instance) & 0x0F) << 0)
	data[0] = (data[0] & ^byte(0x0F << 4)) | byte((uint64(m.FluidType) & 0x0F) << 4)
	binary.LittleEndian.PutUint16(data[1:3], uint16(uint64(int64(math.Round(m.Level / 0.004)))))
	binary.LittleEndian.PutUint32(data[3:7], uint32(uint64(math.Round(m.Capacity / 0.1))))
	return data
}

// BatteryStatus represents PGN 127508 — Battery Status.
type BatteryStatus struct {
	Instance uint8 `json:"instance"`
	Voltage float64 `json:"voltage"` // V
	Current float64 `json:"current"` // A
	Temperature float64 `json:"temperature"` // K
	Sid uint8 `json:"sid"`
}

func (BatteryStatus) PGN() uint32 { return 127508 }

// DecodeBatteryStatus decodes PGN 127508 from raw bytes.
func DecodeBatteryStatus(data []byte) (BatteryStatus, error) {
	if len(data) < 8 {
		return BatteryStatus{}, fmt.Errorf("pgn 127508: need 8 bytes, got %d", len(data))
	}
	var m BatteryStatus
	m.Instance = data[0]
	m.Voltage = float64(binary.LittleEndian.Uint16(data[1:3])) * 0.01
	m.Current = float64(int16(binary.LittleEndian.Uint16(data[3:5]))) * 0.1
	m.Temperature = float64(binary.LittleEndian.Uint16(data[5:7])) * 0.01
	m.Sid = data[7]
	return m, nil
}

// Encode serializes BatteryStatus to raw bytes.
func (m *BatteryStatus) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Instance))
	binary.LittleEndian.PutUint16(data[1:3], uint16(uint64(math.Round(m.Voltage / 0.01))))
	binary.LittleEndian.PutUint16(data[3:5], uint16(uint64(int64(math.Round(m.Current / 0.1)))))
	binary.LittleEndian.PutUint16(data[5:7], uint16(uint64(math.Round(m.Temperature / 0.01))))
	data[7] = byte(uint64(m.Sid))
	return data
}

// BatteryConfigurationStatus represents PGN 127513 — Battery Configuration Status.
type BatteryConfigurationStatus struct {
	Instance uint8 `json:"instance"`
	BatteryType uint8 `json:"battery_type"`
	SupportsEqual uint8 `json:"supports_equal"`
	NominalVoltage float64 `json:"nominal_voltage"` // V
	NominalCapacity float64 `json:"nominal_capacity"` // Ah
	TemperatureCoeff uint8 `json:"temperature_coeff"` // %
	PeukertExponent float64 `json:"peukert_exponent"`
	ChargeEffFactor float64 `json:"charge_eff_factor"` // %
}

func (BatteryConfigurationStatus) PGN() uint32 { return 127513 }

// DecodeBatteryConfigurationStatus decodes PGN 127513 from raw bytes.
func DecodeBatteryConfigurationStatus(data []byte) (BatteryConfigurationStatus, error) {
	if len(data) < 11 {
		return BatteryConfigurationStatus{}, fmt.Errorf("pgn 127513: need 11 bytes, got %d", len(data))
	}
	var m BatteryConfigurationStatus
	m.Instance = data[0]
	m.BatteryType = data[1] & 0x0F
	m.SupportsEqual = (data[1] >> 4) & 0x03
	m.NominalVoltage = float64(binary.LittleEndian.Uint16(data[2:4])) * 0.01
	m.NominalCapacity = float64(binary.LittleEndian.Uint16(data[4:6])) * 1.0
	m.TemperatureCoeff = data[6]
	m.PeukertExponent = float64(int16(binary.LittleEndian.Uint16(data[7:9]))) * 0.002
	m.ChargeEffFactor = float64(int16(binary.LittleEndian.Uint16(data[9:11]))) * 1.0
	return m, nil
}

// Encode serializes BatteryConfigurationStatus to raw bytes.
func (m *BatteryConfigurationStatus) Encode() []byte {
	data := make([]byte, 11)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Instance))
	data[1] = (data[1] & ^byte(0x0F << 0)) | byte((uint64(m.BatteryType) & 0x0F) << 0)
	data[1] = (data[1] & ^byte(0x03 << 4)) | byte((uint64(m.SupportsEqual) & 0x03) << 4)
	binary.LittleEndian.PutUint16(data[2:4], uint16(uint64(math.Round(m.NominalVoltage / 0.01))))
	binary.LittleEndian.PutUint16(data[4:6], uint16(uint64(math.Round(m.NominalCapacity / 1.0))))
	data[6] = byte(uint64(m.TemperatureCoeff))
	binary.LittleEndian.PutUint16(data[7:9], uint16(uint64(int64(math.Round(m.PeukertExponent / 0.002)))))
	binary.LittleEndian.PutUint16(data[9:11], uint16(uint64(int64(math.Round(m.ChargeEffFactor / 1.0)))))
	return data
}

// DCDetailedStatus represents PGN 127506 — DC Detailed Status.
type DCDetailedStatus struct {
	Sid uint8 `json:"sid"`
	Instance uint8 `json:"instance"`
	DcType uint8 `json:"dc_type"`
	StateOfCharge uint8 `json:"state_of_charge"` // %
	StateOfHealth uint8 `json:"state_of_health"` // %
	TimeRemaining float64 `json:"time_remaining"` // s
	RippleVoltage float64 `json:"ripple_voltage"` // V
	CapacityRemaining float64 `json:"capacity_remaining"` // Ah
}

func (DCDetailedStatus) PGN() uint32 { return 127506 }

// DecodeDCDetailedStatus decodes PGN 127506 from raw bytes.
func DecodeDCDetailedStatus(data []byte) (DCDetailedStatus, error) {
	if len(data) < 11 {
		return DCDetailedStatus{}, fmt.Errorf("pgn 127506: need 11 bytes, got %d", len(data))
	}
	var m DCDetailedStatus
	m.Sid = data[0]
	m.Instance = data[1]
	m.DcType = data[2]
	m.StateOfCharge = data[3]
	m.StateOfHealth = data[4]
	m.TimeRemaining = float64(binary.LittleEndian.Uint16(data[5:7])) * 60.0
	m.RippleVoltage = float64(binary.LittleEndian.Uint16(data[7:9])) * 0.001
	m.CapacityRemaining = float64(binary.LittleEndian.Uint16(data[9:11])) * 1.0
	return m, nil
}

// Encode serializes DCDetailedStatus to raw bytes.
func (m *DCDetailedStatus) Encode() []byte {
	data := make([]byte, 11)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	data[1] = byte(uint64(m.Instance))
	data[2] = byte(uint64(m.DcType))
	data[3] = byte(uint64(m.StateOfCharge))
	data[4] = byte(uint64(m.StateOfHealth))
	binary.LittleEndian.PutUint16(data[5:7], uint16(uint64(math.Round(m.TimeRemaining / 60.0))))
	binary.LittleEndian.PutUint16(data[7:9], uint16(uint64(math.Round(m.RippleVoltage / 0.001))))
	binary.LittleEndian.PutUint16(data[9:11], uint16(uint64(math.Round(m.CapacityRemaining / 1.0))))
	return data
}

// ChargerStatus represents PGN 127507 — Charger Status.
type ChargerStatus struct {
	Instance uint8 `json:"instance"`
	BatteryInstance uint8 `json:"battery_instance"`
	OperatingState uint8 `json:"operating_state"`
	ChargeMode uint8 `json:"charge_mode"`
	ChargerEnable uint8 `json:"charger_enable"`
	EqualizationPending uint8 `json:"equalization_pending"`
	EqualizationTime float64 `json:"equalization_time"` // s
}

func (ChargerStatus) PGN() uint32 { return 127507 }

// DecodeChargerStatus decodes PGN 127507 from raw bytes.
func DecodeChargerStatus(data []byte) (ChargerStatus, error) {
	if len(data) < 6 {
		return ChargerStatus{}, fmt.Errorf("pgn 127507: need 6 bytes, got %d", len(data))
	}
	var m ChargerStatus
	m.Instance = data[0]
	m.BatteryInstance = data[1]
	m.OperatingState = data[2] & 0x0F
	m.ChargeMode = (data[2] >> 4) & 0x0F
	m.ChargerEnable = data[3] & 0x03
	m.EqualizationPending = (data[3] >> 2) & 0x03
	m.EqualizationTime = float64(binary.LittleEndian.Uint16(data[4:6])) * 60.0
	return m, nil
}

// Encode serializes ChargerStatus to raw bytes.
func (m *ChargerStatus) Encode() []byte {
	data := make([]byte, 6)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Instance))
	data[1] = byte(uint64(m.BatteryInstance))
	data[2] = (data[2] & ^byte(0x0F << 0)) | byte((uint64(m.OperatingState) & 0x0F) << 0)
	data[2] = (data[2] & ^byte(0x0F << 4)) | byte((uint64(m.ChargeMode) & 0x0F) << 4)
	data[3] = (data[3] & ^byte(0x03 << 0)) | byte((uint64(m.ChargerEnable) & 0x03) << 0)
	data[3] = (data[3] & ^byte(0x03 << 2)) | byte((uint64(m.EqualizationPending) & 0x03) << 2)
	binary.LittleEndian.PutUint16(data[4:6], uint16(uint64(math.Round(m.EqualizationTime / 60.0))))
	return data
}

// WindData represents PGN 130306 — Wind Data.
type WindData struct {
	Sid uint8 `json:"sid"`
	WindSpeed float64 `json:"wind_speed"` // m/s
	WindAngle float64 `json:"wind_angle"` // rad
	WindReference WindReference `json:"wind_reference"`
}

func (WindData) PGN() uint32 { return 130306 }

// DecodeWindData decodes PGN 130306 from raw bytes.
func DecodeWindData(data []byte) (WindData, error) {
	if len(data) < 8 {
		return WindData{}, fmt.Errorf("pgn 130306: need 8 bytes, got %d", len(data))
	}
	var m WindData
	m.Sid = data[0]
	m.WindSpeed = float64(binary.LittleEndian.Uint16(data[1:3])) * 0.01
	m.WindAngle = float64(binary.LittleEndian.Uint16(data[3:5])) * 0.0001
	m.WindReference = WindReference(data[5] & 0x07)
	return m, nil
}

// Encode serializes WindData to raw bytes.
func (m *WindData) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	binary.LittleEndian.PutUint16(data[1:3], uint16(uint64(math.Round(m.WindSpeed / 0.01))))
	binary.LittleEndian.PutUint16(data[3:5], uint16(uint64(math.Round(m.WindAngle / 0.0001))))
	data[5] = (data[5] & ^byte(0x07 << 0)) | byte((uint64(m.WindReference) & 0x07) << 0)
	return data
}

// EnvironmentalParametersOutside represents PGN 130310 — Environmental Parameters Outside.
type EnvironmentalParametersOutside struct {
	Sid uint8 `json:"sid"`
	WaterTemperature float64 `json:"water_temperature"` // K
	OutsideTemperature float64 `json:"outside_temperature"` // K
	AtmosphericPressure float64 `json:"atmospheric_pressure"` // Pa
}

func (EnvironmentalParametersOutside) PGN() uint32 { return 130310 }

// DecodeEnvironmentalParametersOutside decodes PGN 130310 from raw bytes.
func DecodeEnvironmentalParametersOutside(data []byte) (EnvironmentalParametersOutside, error) {
	if len(data) < 9 {
		return EnvironmentalParametersOutside{}, fmt.Errorf("pgn 130310: need 9 bytes, got %d", len(data))
	}
	var m EnvironmentalParametersOutside
	m.Sid = data[0]
	m.WaterTemperature = float64(binary.LittleEndian.Uint16(data[1:3])) * 0.01
	m.OutsideTemperature = float64(binary.LittleEndian.Uint16(data[3:5])) * 0.01
	m.AtmosphericPressure = float64(binary.LittleEndian.Uint16(data[5:7])) * 100.0
	return m, nil
}

// Encode serializes EnvironmentalParametersOutside to raw bytes.
func (m *EnvironmentalParametersOutside) Encode() []byte {
	data := make([]byte, 9)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	binary.LittleEndian.PutUint16(data[1:3], uint16(uint64(math.Round(m.WaterTemperature / 0.01))))
	binary.LittleEndian.PutUint16(data[3:5], uint16(uint64(math.Round(m.OutsideTemperature / 0.01))))
	binary.LittleEndian.PutUint16(data[5:7], uint16(uint64(math.Round(m.AtmosphericPressure / 100.0))))
	return data
}

// EnvironmentalParametersInside represents PGN 130311 — Environmental Parameters Inside.
type EnvironmentalParametersInside struct {
	Sid uint8 `json:"sid"`
	TemperatureSource TemperatureSource `json:"temperature_source"`
	HumiditySource HumiditySource `json:"humidity_source"`
	Temperature float64 `json:"temperature"` // K
	Humidity float64 `json:"humidity"` // %
	AtmosphericPressure float64 `json:"atmospheric_pressure"` // Pa
}

func (EnvironmentalParametersInside) PGN() uint32 { return 130311 }

// DecodeEnvironmentalParametersInside decodes PGN 130311 from raw bytes.
func DecodeEnvironmentalParametersInside(data []byte) (EnvironmentalParametersInside, error) {
	if len(data) < 9 {
		return EnvironmentalParametersInside{}, fmt.Errorf("pgn 130311: need 9 bytes, got %d", len(data))
	}
	var m EnvironmentalParametersInside
	m.Sid = data[0]
	m.TemperatureSource = TemperatureSource(data[1] & 0x3F)
	m.HumiditySource = HumiditySource((data[1] >> 6) & 0x03)
	m.Temperature = float64(binary.LittleEndian.Uint16(data[2:4])) * 0.01
	m.Humidity = float64(int16(binary.LittleEndian.Uint16(data[4:6]))) * 0.004
	m.AtmosphericPressure = float64(binary.LittleEndian.Uint16(data[6:8])) * 100.0
	return m, nil
}

// Encode serializes EnvironmentalParametersInside to raw bytes.
func (m *EnvironmentalParametersInside) Encode() []byte {
	data := make([]byte, 9)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	data[1] = (data[1] & ^byte(0x3F << 0)) | byte((uint64(m.TemperatureSource) & 0x3F) << 0)
	data[1] = (data[1] & ^byte(0x03 << 6)) | byte((uint64(m.HumiditySource) & 0x03) << 6)
	binary.LittleEndian.PutUint16(data[2:4], uint16(uint64(math.Round(m.Temperature / 0.01))))
	binary.LittleEndian.PutUint16(data[4:6], uint16(uint64(int64(math.Round(m.Humidity / 0.004)))))
	binary.LittleEndian.PutUint16(data[6:8], uint16(uint64(math.Round(m.AtmosphericPressure / 100.0))))
	return data
}

// Temperature represents PGN 130312 — Temperature.
type Temperature struct {
	Sid uint8 `json:"sid"`
	Instance uint8 `json:"instance"`
	TemperatureSource TemperatureSource `json:"temperature_source"`
	ActualTemperature float64 `json:"actual_temperature"` // K
	SetTemperature float64 `json:"set_temperature"` // K
}

func (Temperature) PGN() uint32 { return 130312 }

// DecodeTemperature decodes PGN 130312 from raw bytes.
func DecodeTemperature(data []byte) (Temperature, error) {
	if len(data) < 8 {
		return Temperature{}, fmt.Errorf("pgn 130312: need 8 bytes, got %d", len(data))
	}
	var m Temperature
	m.Sid = data[0]
	m.Instance = data[1]
	m.TemperatureSource = TemperatureSource(data[2])
	m.ActualTemperature = float64(binary.LittleEndian.Uint16(data[3:5])) * 0.01
	m.SetTemperature = float64(binary.LittleEndian.Uint16(data[5:7])) * 0.01
	return m, nil
}

// Encode serializes Temperature to raw bytes.
func (m *Temperature) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	data[1] = byte(uint64(m.Instance))
	data[2] = byte(uint64(m.TemperatureSource))
	binary.LittleEndian.PutUint16(data[3:5], uint16(uint64(math.Round(m.ActualTemperature / 0.01))))
	binary.LittleEndian.PutUint16(data[5:7], uint16(uint64(math.Round(m.SetTemperature / 0.01))))
	return data
}

// Humidity represents PGN 130313 — Humidity.
type Humidity struct {
	Sid uint8 `json:"sid"`
	Instance uint8 `json:"instance"`
	HumiditySource HumiditySource `json:"humidity_source"`
	ActualHumidity float64 `json:"actual_humidity"` // %
	SetHumidity float64 `json:"set_humidity"` // %
}

func (Humidity) PGN() uint32 { return 130313 }

// DecodeHumidity decodes PGN 130313 from raw bytes.
func DecodeHumidity(data []byte) (Humidity, error) {
	if len(data) < 8 {
		return Humidity{}, fmt.Errorf("pgn 130313: need 8 bytes, got %d", len(data))
	}
	var m Humidity
	m.Sid = data[0]
	m.Instance = data[1]
	m.HumiditySource = HumiditySource(data[2])
	m.ActualHumidity = float64(binary.LittleEndian.Uint16(data[3:5])) * 0.004
	m.SetHumidity = float64(binary.LittleEndian.Uint16(data[5:7])) * 0.004
	return m, nil
}

// Encode serializes Humidity to raw bytes.
func (m *Humidity) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	data[1] = byte(uint64(m.Instance))
	data[2] = byte(uint64(m.HumiditySource))
	binary.LittleEndian.PutUint16(data[3:5], uint16(uint64(math.Round(m.ActualHumidity / 0.004))))
	binary.LittleEndian.PutUint16(data[5:7], uint16(uint64(math.Round(m.SetHumidity / 0.004))))
	return data
}

// ActualPressure represents PGN 130314 — Actual Pressure.
type ActualPressure struct {
	Sid uint8 `json:"sid"`
	Instance uint8 `json:"instance"`
	PressureSource PressureSource `json:"pressure_source"`
	Pressure float64 `json:"pressure"` // Pa
}

func (ActualPressure) PGN() uint32 { return 130314 }

// DecodeActualPressure decodes PGN 130314 from raw bytes.
func DecodeActualPressure(data []byte) (ActualPressure, error) {
	if len(data) < 8 {
		return ActualPressure{}, fmt.Errorf("pgn 130314: need 8 bytes, got %d", len(data))
	}
	var m ActualPressure
	m.Sid = data[0]
	m.Instance = data[1]
	m.PressureSource = PressureSource(data[2])
	m.Pressure = float64(binary.LittleEndian.Uint32(data[3:7])) * 0.1
	return m, nil
}

// Encode serializes ActualPressure to raw bytes.
func (m *ActualPressure) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	data[1] = byte(uint64(m.Instance))
	data[2] = byte(uint64(m.PressureSource))
	binary.LittleEndian.PutUint32(data[3:7], uint32(uint64(math.Round(m.Pressure / 0.1))))
	return data
}

// TemperatureExtendedRange represents PGN 130316 — Temperature Extended Range.
type TemperatureExtendedRange struct {
	Sid uint8 `json:"sid"`
	Instance uint8 `json:"instance"`
	TemperatureSource TemperatureSource `json:"temperature_source"`
	ActualTemperature float64 `json:"actual_temperature"` // K
	SetTemperature float64 `json:"set_temperature"` // K
}

func (TemperatureExtendedRange) PGN() uint32 { return 130316 }

// DecodeTemperatureExtendedRange decodes PGN 130316 from raw bytes.
func DecodeTemperatureExtendedRange(data []byte) (TemperatureExtendedRange, error) {
	if len(data) < 8 {
		return TemperatureExtendedRange{}, fmt.Errorf("pgn 130316: need 8 bytes, got %d", len(data))
	}
	var m TemperatureExtendedRange
	m.Sid = data[0]
	m.Instance = data[1]
	m.TemperatureSource = TemperatureSource(data[2])
	m.ActualTemperature = float64((binary.LittleEndian.Uint32(data[3:7]) >> 0) & 0x00FFFFFF) * 0.001
	m.SetTemperature = float64(binary.LittleEndian.Uint16(data[6:8])) * 0.1
	return m, nil
}

// Encode serializes TemperatureExtendedRange to raw bytes.
func (m *TemperatureExtendedRange) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	data[1] = byte(uint64(m.Instance))
	data[2] = byte(uint64(m.TemperatureSource))
	{
		v := binary.LittleEndian.Uint32(data[3:7])
		v = (v & ^uint32(0x00FFFFFF << 0)) | uint32((uint64(math.Round(m.ActualTemperature / 0.001)) & 0x00FFFFFF) << 0)
		binary.LittleEndian.PutUint32(data[3:7], v)
	}
	binary.LittleEndian.PutUint16(data[6:8], uint16(uint64(math.Round(m.SetTemperature / 0.1))))
	return data
}

// VesselHeading represents PGN 127250 — Vessel Heading.
type VesselHeading struct {
	Sid uint8 `json:"sid"`
	Heading float64 `json:"heading"` // rad
	Deviation float64 `json:"deviation"` // rad
	Variation float64 `json:"variation"` // rad
	HeadingReference HeadingReference `json:"heading_reference"`
}

func (VesselHeading) PGN() uint32 { return 127250 }

// DecodeVesselHeading decodes PGN 127250 from raw bytes.
func DecodeVesselHeading(data []byte) (VesselHeading, error) {
	if len(data) < 8 {
		return VesselHeading{}, fmt.Errorf("pgn 127250: need 8 bytes, got %d", len(data))
	}
	var m VesselHeading
	m.Sid = data[0]
	m.Heading = float64(binary.LittleEndian.Uint16(data[1:3])) * 0.0001
	m.Deviation = float64(int16(binary.LittleEndian.Uint16(data[3:5]))) * 0.0001
	m.Variation = float64(int16(binary.LittleEndian.Uint16(data[5:7]))) * 0.0001
	m.HeadingReference = HeadingReference(data[7] & 0x03)
	return m, nil
}

// Encode serializes VesselHeading to raw bytes.
func (m *VesselHeading) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	binary.LittleEndian.PutUint16(data[1:3], uint16(uint64(math.Round(m.Heading / 0.0001))))
	binary.LittleEndian.PutUint16(data[3:5], uint16(uint64(int64(math.Round(m.Deviation / 0.0001)))))
	binary.LittleEndian.PutUint16(data[5:7], uint16(uint64(int64(math.Round(m.Variation / 0.0001)))))
	data[7] = (data[7] & ^byte(0x03 << 0)) | byte((uint64(m.HeadingReference) & 0x03) << 0)
	return data
}

// RateOfTurn represents PGN 127251 — Rate of Turn.
type RateOfTurn struct {
	Sid uint8 `json:"sid"`
	Rate float64 `json:"rate"` // rad/s
}

func (RateOfTurn) PGN() uint32 { return 127251 }

// DecodeRateOfTurn decodes PGN 127251 from raw bytes.
func DecodeRateOfTurn(data []byte) (RateOfTurn, error) {
	if len(data) < 8 {
		return RateOfTurn{}, fmt.Errorf("pgn 127251: need 8 bytes, got %d", len(data))
	}
	var m RateOfTurn
	m.Sid = data[0]
	m.Rate = float64(int32(binary.LittleEndian.Uint32(data[1:5]))) * 3.125e-08
	return m, nil
}

// Encode serializes RateOfTurn to raw bytes.
func (m *RateOfTurn) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	binary.LittleEndian.PutUint32(data[1:5], uint32(uint64(int64(math.Round(m.Rate / 3.125e-08)))))
	return data
}

// Attitude represents PGN 127257 — Attitude.
type Attitude struct {
	Sid uint8 `json:"sid"`
	Yaw float64 `json:"yaw"` // rad
	Pitch float64 `json:"pitch"` // rad
	Roll float64 `json:"roll"` // rad
}

func (Attitude) PGN() uint32 { return 127257 }

// DecodeAttitude decodes PGN 127257 from raw bytes.
func DecodeAttitude(data []byte) (Attitude, error) {
	if len(data) < 8 {
		return Attitude{}, fmt.Errorf("pgn 127257: need 8 bytes, got %d", len(data))
	}
	var m Attitude
	m.Sid = data[0]
	m.Yaw = float64(int16(binary.LittleEndian.Uint16(data[1:3]))) * 0.0001
	m.Pitch = float64(int16(binary.LittleEndian.Uint16(data[3:5]))) * 0.0001
	m.Roll = float64(int16(binary.LittleEndian.Uint16(data[5:7]))) * 0.0001
	return m, nil
}

// Encode serializes Attitude to raw bytes.
func (m *Attitude) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	binary.LittleEndian.PutUint16(data[1:3], uint16(uint64(int64(math.Round(m.Yaw / 0.0001)))))
	binary.LittleEndian.PutUint16(data[3:5], uint16(uint64(int64(math.Round(m.Pitch / 0.0001)))))
	binary.LittleEndian.PutUint16(data[5:7], uint16(uint64(int64(math.Round(m.Roll / 0.0001)))))
	return data
}

// SpeedWaterReferenced represents PGN 128259 — Speed Water Referenced.
type SpeedWaterReferenced struct {
	Sid uint8 `json:"sid"`
	SpeedWater float64 `json:"speed_water"` // m/s
	SpeedGround float64 `json:"speed_ground"` // m/s
	SpeedType SpeedType `json:"speed_type"`
}

func (SpeedWaterReferenced) PGN() uint32 { return 128259 }

// DecodeSpeedWaterReferenced decodes PGN 128259 from raw bytes.
func DecodeSpeedWaterReferenced(data []byte) (SpeedWaterReferenced, error) {
	if len(data) < 7 {
		return SpeedWaterReferenced{}, fmt.Errorf("pgn 128259: need 7 bytes, got %d", len(data))
	}
	var m SpeedWaterReferenced
	m.Sid = data[0]
	m.SpeedWater = float64(binary.LittleEndian.Uint16(data[1:3])) * 0.01
	m.SpeedGround = float64(binary.LittleEndian.Uint16(data[3:5])) * 0.01
	m.SpeedType = SpeedType(data[5] & 0x0F)
	return m, nil
}

// Encode serializes SpeedWaterReferenced to raw bytes.
func (m *SpeedWaterReferenced) Encode() []byte {
	data := make([]byte, 7)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	binary.LittleEndian.PutUint16(data[1:3], uint16(uint64(math.Round(m.SpeedWater / 0.01))))
	binary.LittleEndian.PutUint16(data[3:5], uint16(uint64(math.Round(m.SpeedGround / 0.01))))
	data[5] = (data[5] & ^byte(0x0F << 0)) | byte((uint64(m.SpeedType) & 0x0F) << 0)
	return data
}

// WaterDepth represents PGN 128267 — Water Depth.
type WaterDepth struct {
	Sid uint8 `json:"sid"`
	Depth float64 `json:"depth"` // m
	Offset float64 `json:"offset"` // m
	MaxRange float64 `json:"max_range"` // m
}

func (WaterDepth) PGN() uint32 { return 128267 }

// DecodeWaterDepth decodes PGN 128267 from raw bytes.
func DecodeWaterDepth(data []byte) (WaterDepth, error) {
	if len(data) < 11 {
		return WaterDepth{}, fmt.Errorf("pgn 128267: need 11 bytes, got %d", len(data))
	}
	var m WaterDepth
	m.Sid = data[0]
	m.Depth = float64(binary.LittleEndian.Uint32(data[1:5])) * 0.01
	m.Offset = float64(int16(binary.LittleEndian.Uint16(data[5:7]))) * 0.001
	m.MaxRange = float64(binary.LittleEndian.Uint32(data[7:11])) * 0.01
	return m, nil
}

// Encode serializes WaterDepth to raw bytes.
func (m *WaterDepth) Encode() []byte {
	data := make([]byte, 11)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	binary.LittleEndian.PutUint32(data[1:5], uint32(uint64(math.Round(m.Depth / 0.01))))
	binary.LittleEndian.PutUint16(data[5:7], uint16(uint64(int64(math.Round(m.Offset / 0.001)))))
	binary.LittleEndian.PutUint32(data[7:11], uint32(uint64(math.Round(m.MaxRange / 0.01))))
	return data
}

// PositionRapidUpdate represents PGN 129025 — Position Rapid Update.
type PositionRapidUpdate struct {
	Latitude float64 `json:"latitude"` // deg
	Longitude float64 `json:"longitude"` // deg
}

func (PositionRapidUpdate) PGN() uint32 { return 129025 }

// DecodePositionRapidUpdate decodes PGN 129025 from raw bytes.
func DecodePositionRapidUpdate(data []byte) (PositionRapidUpdate, error) {
	if len(data) < 8 {
		return PositionRapidUpdate{}, fmt.Errorf("pgn 129025: need 8 bytes, got %d", len(data))
	}
	var m PositionRapidUpdate
	m.Latitude = float64(int32(binary.LittleEndian.Uint32(data[0:4]))) * 1e-07
	m.Longitude = float64(int32(binary.LittleEndian.Uint32(data[4:8]))) * 1e-07
	return m, nil
}

// Encode serializes PositionRapidUpdate to raw bytes.
func (m *PositionRapidUpdate) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	binary.LittleEndian.PutUint32(data[0:4], uint32(uint64(int64(math.Round(m.Latitude / 1e-07)))))
	binary.LittleEndian.PutUint32(data[4:8], uint32(uint64(int64(math.Round(m.Longitude / 1e-07)))))
	return data
}

// COGSOGRapidUpdate represents PGN 129026 — COG SOG Rapid Update.
type COGSOGRapidUpdate struct {
	Sid uint8 `json:"sid"`
	CogReference HeadingReference `json:"cog_reference"`
	Cog float64 `json:"cog"` // rad
	Sog float64 `json:"sog"` // m/s
}

func (COGSOGRapidUpdate) PGN() uint32 { return 129026 }

// DecodeCOGSOGRapidUpdate decodes PGN 129026 from raw bytes.
func DecodeCOGSOGRapidUpdate(data []byte) (COGSOGRapidUpdate, error) {
	if len(data) < 8 {
		return COGSOGRapidUpdate{}, fmt.Errorf("pgn 129026: need 8 bytes, got %d", len(data))
	}
	var m COGSOGRapidUpdate
	m.Sid = data[0]
	m.CogReference = HeadingReference(data[1] & 0x03)
	m.Cog = float64(binary.LittleEndian.Uint16(data[2:4])) * 0.0001
	m.Sog = float64(binary.LittleEndian.Uint16(data[4:6])) * 0.01
	return m, nil
}

// Encode serializes COGSOGRapidUpdate to raw bytes.
func (m *COGSOGRapidUpdate) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	data[1] = (data[1] & ^byte(0x03 << 0)) | byte((uint64(m.CogReference) & 0x03) << 0)
	binary.LittleEndian.PutUint16(data[2:4], uint16(uint64(math.Round(m.Cog / 0.0001))))
	binary.LittleEndian.PutUint16(data[4:6], uint16(uint64(math.Round(m.Sog / 0.01))))
	return data
}

// GNSSPositionData represents PGN 129029 — GNSS Position Data.
type GNSSPositionData struct {
	Sid uint8 `json:"sid"`
	DaysSince1970 uint16 `json:"days_since_1970"`
	SecondsToday float64 `json:"seconds_today"` // s
	Latitude float64 `json:"latitude"` // deg
	Longitude float64 `json:"longitude"` // deg
	Altitude float64 `json:"altitude"` // m
	GnssType uint8 `json:"gnss_type"`
	GnssMethod uint8 `json:"gnss_method"`
	Integrity uint8 `json:"integrity"`
	NumSvs uint8 `json:"num_svs"`
	Hdop float64 `json:"hdop"`
	Pdop float64 `json:"pdop"`
	GeoidalSep float64 `json:"geoidal_sep"` // m
	NumRefStations uint8 `json:"num_ref_stations"`
}

func (GNSSPositionData) PGN() uint32 { return 129029 }

// DecodeGNSSPositionData decodes PGN 129029 from raw bytes.
func DecodeGNSSPositionData(data []byte) (GNSSPositionData, error) {
	if len(data) < 43 {
		return GNSSPositionData{}, fmt.Errorf("pgn 129029: need 43 bytes, got %d", len(data))
	}
	var m GNSSPositionData
	m.Sid = data[0]
	m.DaysSince1970 = binary.LittleEndian.Uint16(data[1:3])
	m.SecondsToday = float64(binary.LittleEndian.Uint32(data[3:7])) * 0.0001
	m.Latitude = float64(int64(binary.LittleEndian.Uint64(data[7:15]))) * 1e-16
	m.Longitude = float64(int64(binary.LittleEndian.Uint64(data[15:23]))) * 1e-16
	m.Altitude = float64(int64(binary.LittleEndian.Uint64(data[23:31]))) * 1e-06
	m.GnssType = data[31] & 0x0F
	m.GnssMethod = (data[31] >> 4) & 0x0F
	m.Integrity = data[32] & 0x03
	m.NumSvs = data[33]
	m.Hdop = float64(int16(binary.LittleEndian.Uint16(data[34:36]))) * 0.01
	m.Pdop = float64(int16(binary.LittleEndian.Uint16(data[36:38]))) * 0.01
	m.GeoidalSep = float64(int32(binary.LittleEndian.Uint32(data[38:42]))) * 0.01
	m.NumRefStations = data[42]
	return m, nil
}

// Encode serializes GNSSPositionData to raw bytes.
func (m *GNSSPositionData) Encode() []byte {
	data := make([]byte, 43)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	binary.LittleEndian.PutUint16(data[1:3], uint16(uint64(m.DaysSince1970)))
	binary.LittleEndian.PutUint32(data[3:7], uint32(uint64(math.Round(m.SecondsToday / 0.0001))))
	binary.LittleEndian.PutUint64(data[7:15], uint64(uint64(int64(math.Round(m.Latitude / 1e-16)))))
	binary.LittleEndian.PutUint64(data[15:23], uint64(uint64(int64(math.Round(m.Longitude / 1e-16)))))
	binary.LittleEndian.PutUint64(data[23:31], uint64(uint64(int64(math.Round(m.Altitude / 1e-06)))))
	data[31] = (data[31] & ^byte(0x0F << 0)) | byte((uint64(m.GnssType) & 0x0F) << 0)
	data[31] = (data[31] & ^byte(0x0F << 4)) | byte((uint64(m.GnssMethod) & 0x0F) << 4)
	data[32] = (data[32] & ^byte(0x03 << 0)) | byte((uint64(m.Integrity) & 0x03) << 0)
	data[33] = byte(uint64(m.NumSvs))
	binary.LittleEndian.PutUint16(data[34:36], uint16(uint64(int64(math.Round(m.Hdop / 0.01)))))
	binary.LittleEndian.PutUint16(data[36:38], uint16(uint64(int64(math.Round(m.Pdop / 0.01)))))
	binary.LittleEndian.PutUint32(data[38:42], uint32(uint64(int64(math.Round(m.GeoidalSep / 0.01)))))
	data[42] = byte(uint64(m.NumRefStations))
	return data
}

// CrossTrackError represents PGN 129283 — Cross Track Error.
type CrossTrackError struct {
	Sid uint8 `json:"sid"`
	XteMode uint8 `json:"xte_mode"`
	NavTerm uint8 `json:"nav_term"`
	Xte float64 `json:"xte"` // m
}

func (CrossTrackError) PGN() uint32 { return 129283 }

// DecodeCrossTrackError decodes PGN 129283 from raw bytes.
func DecodeCrossTrackError(data []byte) (CrossTrackError, error) {
	if len(data) < 8 {
		return CrossTrackError{}, fmt.Errorf("pgn 129283: need 8 bytes, got %d", len(data))
	}
	var m CrossTrackError
	m.Sid = data[0]
	m.XteMode = data[1] & 0x0F
	m.NavTerm = (data[1] >> 6) & 0x03
	m.Xte = float64(int32(binary.LittleEndian.Uint32(data[2:6]))) * 0.01
	return m, nil
}

// Encode serializes CrossTrackError to raw bytes.
func (m *CrossTrackError) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	data[1] = (data[1] & ^byte(0x0F << 0)) | byte((uint64(m.XteMode) & 0x0F) << 0)
	data[1] = (data[1] & ^byte(0x03 << 6)) | byte((uint64(m.NavTerm) & 0x03) << 6)
	binary.LittleEndian.PutUint32(data[2:6], uint32(uint64(int64(math.Round(m.Xte / 0.01)))))
	return data
}

// NavigationData represents PGN 129284 — Navigation Data.
type NavigationData struct {
	Sid uint8 `json:"sid"`
	DistanceToWp float64 `json:"distance_to_wp"` // m
	BearingReference DirectionReference `json:"bearing_reference"`
	PerpCrossed uint8 `json:"perp_crossed"`
	ArrivalCircleEntered uint8 `json:"arrival_circle_entered"`
	CalcType uint8 `json:"calc_type"`
	EtaTime float64 `json:"eta_time"` // s
	EtaDate uint16 `json:"eta_date"`
	BearingOriginToDest float64 `json:"bearing_origin_to_dest"` // rad
	BearingPositionToDest float64 `json:"bearing_position_to_dest"` // rad
	OriginWpNumber uint32 `json:"origin_wp_number"`
	DestWpNumber uint32 `json:"dest_wp_number"`
	DestLatitude float64 `json:"dest_latitude"` // deg
	DestLongitude float64 `json:"dest_longitude"` // deg
	WpClosingVelocity float64 `json:"wp_closing_velocity"` // m/s
}

func (NavigationData) PGN() uint32 { return 129284 }

// DecodeNavigationData decodes PGN 129284 from raw bytes.
func DecodeNavigationData(data []byte) (NavigationData, error) {
	if len(data) < 34 {
		return NavigationData{}, fmt.Errorf("pgn 129284: need 34 bytes, got %d", len(data))
	}
	var m NavigationData
	m.Sid = data[0]
	m.DistanceToWp = float64(binary.LittleEndian.Uint32(data[1:5])) * 0.01
	m.BearingReference = DirectionReference(data[5] & 0x03)
	m.PerpCrossed = (data[5] >> 2) & 0x03
	m.ArrivalCircleEntered = (data[5] >> 4) & 0x03
	m.CalcType = (data[5] >> 6) & 0x03
	m.EtaTime = float64(binary.LittleEndian.Uint32(data[6:10])) * 0.0001
	m.EtaDate = binary.LittleEndian.Uint16(data[10:12])
	m.BearingOriginToDest = float64(binary.LittleEndian.Uint16(data[12:14])) * 0.0001
	m.BearingPositionToDest = float64(binary.LittleEndian.Uint16(data[14:16])) * 0.0001
	m.OriginWpNumber = binary.LittleEndian.Uint32(data[16:20])
	m.DestWpNumber = binary.LittleEndian.Uint32(data[20:24])
	m.DestLatitude = float64(int32(binary.LittleEndian.Uint32(data[24:28]))) * 1e-07
	m.DestLongitude = float64(int32(binary.LittleEndian.Uint32(data[28:32]))) * 1e-07
	m.WpClosingVelocity = float64(int16(binary.LittleEndian.Uint16(data[32:34]))) * 0.01
	return m, nil
}

// Encode serializes NavigationData to raw bytes.
func (m *NavigationData) Encode() []byte {
	data := make([]byte, 34)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	binary.LittleEndian.PutUint32(data[1:5], uint32(uint64(math.Round(m.DistanceToWp / 0.01))))
	data[5] = (data[5] & ^byte(0x03 << 0)) | byte((uint64(m.BearingReference) & 0x03) << 0)
	data[5] = (data[5] & ^byte(0x03 << 2)) | byte((uint64(m.PerpCrossed) & 0x03) << 2)
	data[5] = (data[5] & ^byte(0x03 << 4)) | byte((uint64(m.ArrivalCircleEntered) & 0x03) << 4)
	data[5] = (data[5] & ^byte(0x03 << 6)) | byte((uint64(m.CalcType) & 0x03) << 6)
	binary.LittleEndian.PutUint32(data[6:10], uint32(uint64(math.Round(m.EtaTime / 0.0001))))
	binary.LittleEndian.PutUint16(data[10:12], uint16(uint64(m.EtaDate)))
	binary.LittleEndian.PutUint16(data[12:14], uint16(uint64(math.Round(m.BearingOriginToDest / 0.0001))))
	binary.LittleEndian.PutUint16(data[14:16], uint16(uint64(math.Round(m.BearingPositionToDest / 0.0001))))
	binary.LittleEndian.PutUint32(data[16:20], uint32(uint64(m.OriginWpNumber)))
	binary.LittleEndian.PutUint32(data[20:24], uint32(uint64(m.DestWpNumber)))
	binary.LittleEndian.PutUint32(data[24:28], uint32(uint64(int64(math.Round(m.DestLatitude / 1e-07)))))
	binary.LittleEndian.PutUint32(data[28:32], uint32(uint64(int64(math.Round(m.DestLongitude / 1e-07)))))
	binary.LittleEndian.PutUint16(data[32:34], uint16(uint64(int64(math.Round(m.WpClosingVelocity / 0.01)))))
	return data
}

// ISOAddressClaim represents PGN 60928 — ISO Address Claim.
type ISOAddressClaim struct {
	UniqueNumber uint32 `json:"unique_number"`
	ManufacturerCode uint16 `json:"manufacturer_code"`
	DeviceInstance uint8 `json:"device_instance"`
	DeviceFunction uint8 `json:"device_function"`
	DeviceClass uint8 `json:"device_class"`
	SystemInstance uint8 `json:"system_instance"`
	IndustryGroup uint8 `json:"industry_group"`
	ArbitraryAddress uint8 `json:"arbitrary_address"`
}

func (ISOAddressClaim) PGN() uint32 { return 60928 }

// DecodeISOAddressClaim decodes PGN 60928 from raw bytes.
func DecodeISOAddressClaim(data []byte) (ISOAddressClaim, error) {
	if len(data) < 8 {
		return ISOAddressClaim{}, fmt.Errorf("pgn 60928: need 8 bytes, got %d", len(data))
	}
	var m ISOAddressClaim
	m.UniqueNumber = (binary.LittleEndian.Uint32(data[0:4]) >> 0) & 0x001FFFFF
	m.ManufacturerCode = (binary.LittleEndian.Uint16(data[2:4]) >> 5) & 0x07FF
	m.DeviceInstance = data[4]
	m.DeviceFunction = data[5]
	m.DeviceClass = (data[6] >> 1) & 0x7F
	m.SystemInstance = data[7] & 0x0F
	m.IndustryGroup = (data[7] >> 4) & 0x07
	m.ArbitraryAddress = (data[7] >> 7) & 0x01
	return m, nil
}

// Encode serializes ISOAddressClaim to raw bytes.
func (m *ISOAddressClaim) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	{
		v := binary.LittleEndian.Uint32(data[0:4])
		v = (v & ^uint32(0x001FFFFF << 0)) | uint32((uint64(m.UniqueNumber) & 0x001FFFFF) << 0)
		binary.LittleEndian.PutUint32(data[0:4], v)
	}
	{
		v := binary.LittleEndian.Uint16(data[2:4])
		v = (v & ^uint16(0x07FF << 5)) | uint16((uint64(m.ManufacturerCode) & 0x07FF) << 5)
		binary.LittleEndian.PutUint16(data[2:4], v)
	}
	data[4] = byte(uint64(m.DeviceInstance))
	data[5] = byte(uint64(m.DeviceFunction))
	data[6] = (data[6] & ^byte(0x7F << 1)) | byte((uint64(m.DeviceClass) & 0x7F) << 1)
	data[7] = (data[7] & ^byte(0x0F << 0)) | byte((uint64(m.SystemInstance) & 0x0F) << 0)
	data[7] = (data[7] & ^byte(0x07 << 4)) | byte((uint64(m.IndustryGroup) & 0x07) << 4)
	data[7] = (data[7] & ^byte(0x01 << 7)) | byte((uint64(m.ArbitraryAddress) & 0x01) << 7)
	return data
}

// ProductInformation represents PGN 126996 — Product Information.
type ProductInformation struct {
	NmeaVersion uint16 `json:"nmea_version"`
	ProductCode uint16 `json:"product_code"`
	ModelId string `json:"model_id"`
	SoftwareVersion string `json:"software_version"`
	ModelVersion string `json:"model_version"`
	ModelSerial string `json:"model_serial"`
	CertLevel uint8 `json:"cert_level"`
	LoadEquiv uint8 `json:"load_equiv"`
}

func (ProductInformation) PGN() uint32 { return 126996 }

// DecodeProductInformation decodes PGN 126996 from raw bytes.
func DecodeProductInformation(data []byte) (ProductInformation, error) {
	if len(data) < 134 {
		return ProductInformation{}, fmt.Errorf("pgn 126996: need 134 bytes, got %d", len(data))
	}
	var m ProductInformation
	m.NmeaVersion = binary.LittleEndian.Uint16(data[0:2])
	m.ProductCode = binary.LittleEndian.Uint16(data[2:4])
	m.ModelId = decodeFixedStr(data[4:36])
	m.SoftwareVersion = decodeFixedStr(data[36:76])
	m.ModelVersion = decodeFixedStr(data[76:100])
	m.ModelSerial = decodeFixedStr(data[100:132])
	m.CertLevel = data[132]
	m.LoadEquiv = data[133]
	return m, nil
}

// Encode serializes ProductInformation to raw bytes.
func (m *ProductInformation) Encode() []byte {
	data := make([]byte, 134)
	for i := range data { data[i] = 0xFF }
	binary.LittleEndian.PutUint16(data[0:2], uint16(uint64(m.NmeaVersion)))
	binary.LittleEndian.PutUint16(data[2:4], uint16(uint64(m.ProductCode)))
	encodeFixedStr(data[4:36], m.ModelId)
	encodeFixedStr(data[36:76], m.SoftwareVersion)
	encodeFixedStr(data[76:100], m.ModelVersion)
	encodeFixedStr(data[100:132], m.ModelSerial)
	data[132] = byte(uint64(m.CertLevel))
	data[133] = byte(uint64(m.LoadEquiv))
	return data
}

// SystemTime represents PGN 126992 — System Time.
type SystemTime struct {
	Sid uint8 `json:"sid"`
	TimeSource uint8 `json:"time_source"`
	DaysSince1970 uint16 `json:"days_since_1970"`
	SecondsToday float64 `json:"seconds_today"` // s
}

func (SystemTime) PGN() uint32 { return 126992 }

// DecodeSystemTime decodes PGN 126992 from raw bytes.
func DecodeSystemTime(data []byte) (SystemTime, error) {
	if len(data) < 8 {
		return SystemTime{}, fmt.Errorf("pgn 126992: need 8 bytes, got %d", len(data))
	}
	var m SystemTime
	m.Sid = data[0]
	m.TimeSource = data[1] & 0x0F
	m.DaysSince1970 = binary.LittleEndian.Uint16(data[2:4])
	m.SecondsToday = float64(binary.LittleEndian.Uint32(data[4:8])) * 0.0001
	return m, nil
}

// Encode serializes SystemTime to raw bytes.
func (m *SystemTime) Encode() []byte {
	data := make([]byte, 8)
	for i := range data { data[i] = 0xFF }
	data[0] = byte(uint64(m.Sid))
	data[1] = (data[1] & ^byte(0x0F << 0)) | byte((uint64(m.TimeSource) & 0x0F) << 0)
	binary.LittleEndian.PutUint16(data[2:4], uint16(uint64(m.DaysSince1970)))
	binary.LittleEndian.PutUint32(data[4:8], uint32(uint64(math.Round(m.SecondsToday / 0.0001))))
	return data
}

// PGNInfo describes a registered PGN type.
type PGNInfo struct {
	PGN         uint32
	Description string
	Decode      func([]byte) (any, error)
}

// Registry maps PGN numbers to their decoders.
var Registry = map[uint32]PGNInfo{
	127488: {PGN: 127488, Description: "Engine Parameters Rapid Update", Decode: func(data []byte) (any, error) { return DecodeEngineParametersRapidUpdate(data) }},
	127489: {PGN: 127489, Description: "Engine Parameters Dynamic", Decode: func(data []byte) (any, error) { return DecodeEngineParametersDynamic(data) }},
	127505: {PGN: 127505, Description: "Fluid Level", Decode: func(data []byte) (any, error) { return DecodeFluidLevel(data) }},
	127508: {PGN: 127508, Description: "Battery Status", Decode: func(data []byte) (any, error) { return DecodeBatteryStatus(data) }},
	127513: {PGN: 127513, Description: "Battery Configuration Status", Decode: func(data []byte) (any, error) { return DecodeBatteryConfigurationStatus(data) }},
	127506: {PGN: 127506, Description: "DC Detailed Status", Decode: func(data []byte) (any, error) { return DecodeDCDetailedStatus(data) }},
	127507: {PGN: 127507, Description: "Charger Status", Decode: func(data []byte) (any, error) { return DecodeChargerStatus(data) }},
	130306: {PGN: 130306, Description: "Wind Data", Decode: func(data []byte) (any, error) { return DecodeWindData(data) }},
	130310: {PGN: 130310, Description: "Environmental Parameters Outside", Decode: func(data []byte) (any, error) { return DecodeEnvironmentalParametersOutside(data) }},
	130311: {PGN: 130311, Description: "Environmental Parameters Inside", Decode: func(data []byte) (any, error) { return DecodeEnvironmentalParametersInside(data) }},
	130312: {PGN: 130312, Description: "Temperature", Decode: func(data []byte) (any, error) { return DecodeTemperature(data) }},
	130313: {PGN: 130313, Description: "Humidity", Decode: func(data []byte) (any, error) { return DecodeHumidity(data) }},
	130314: {PGN: 130314, Description: "Actual Pressure", Decode: func(data []byte) (any, error) { return DecodeActualPressure(data) }},
	130316: {PGN: 130316, Description: "Temperature Extended Range", Decode: func(data []byte) (any, error) { return DecodeTemperatureExtendedRange(data) }},
	127250: {PGN: 127250, Description: "Vessel Heading", Decode: func(data []byte) (any, error) { return DecodeVesselHeading(data) }},
	127251: {PGN: 127251, Description: "Rate of Turn", Decode: func(data []byte) (any, error) { return DecodeRateOfTurn(data) }},
	127257: {PGN: 127257, Description: "Attitude", Decode: func(data []byte) (any, error) { return DecodeAttitude(data) }},
	128259: {PGN: 128259, Description: "Speed Water Referenced", Decode: func(data []byte) (any, error) { return DecodeSpeedWaterReferenced(data) }},
	128267: {PGN: 128267, Description: "Water Depth", Decode: func(data []byte) (any, error) { return DecodeWaterDepth(data) }},
	129025: {PGN: 129025, Description: "Position Rapid Update", Decode: func(data []byte) (any, error) { return DecodePositionRapidUpdate(data) }},
	129026: {PGN: 129026, Description: "COG SOG Rapid Update", Decode: func(data []byte) (any, error) { return DecodeCOGSOGRapidUpdate(data) }},
	129029: {PGN: 129029, Description: "GNSS Position Data", Decode: func(data []byte) (any, error) { return DecodeGNSSPositionData(data) }},
	129283: {PGN: 129283, Description: "Cross Track Error", Decode: func(data []byte) (any, error) { return DecodeCrossTrackError(data) }},
	129284: {PGN: 129284, Description: "Navigation Data", Decode: func(data []byte) (any, error) { return DecodeNavigationData(data) }},
	60928: {PGN: 60928, Description: "ISO Address Claim", Decode: func(data []byte) (any, error) { return DecodeISOAddressClaim(data) }},
	126996: {PGN: 126996, Description: "Product Information", Decode: func(data []byte) (any, error) { return DecodeProductInformation(data) }},
	126992: {PGN: 126992, Description: "System Time", Decode: func(data []byte) (any, error) { return DecodeSystemTime(data) }},
}
