package pgngen

import (
	"fmt"
	"strings"
)

// GenerateProto produces a Protocol Buffers v3 definition for the schema.
func GenerateProto(s *Schema, pkg string) string {
	var b strings.Builder

	b.WriteString("// Code generated by pgngen; DO NOT EDIT.\n\n")
	b.WriteString("syntax = \"proto3\";\n\n")
	b.WriteString(fmt.Sprintf("package %s;\n\n", pkg))
	b.WriteString(fmt.Sprintf("option go_package = \"%s\";\n\n", pkg))

	// Enums
	for _, e := range s.Enums {
		b.WriteString(fmt.Sprintf("enum %s {\n", e.Name))
		// proto3 requires a zero value
		hasZero := false
		for _, v := range e.Values {
			if v.Value == 0 {
				hasZero = true
				break
			}
		}
		if !hasZero {
			b.WriteString(fmt.Sprintf("  %s_UNSPECIFIED = 0;\n", toScreamingSnake(e.Name)))
		}
		for _, v := range e.Values {
			constName := toScreamingSnake(e.Name) + "_" + toScreamingSnake(v.Name)
			b.WriteString(fmt.Sprintf("  %s = %d;\n", constName, v.Value))
		}
		b.WriteString("}\n\n")
	}

	// Messages
	for _, p := range s.PGNs {
		msgName := toPascal(p.Description)
		b.WriteString(fmt.Sprintf("// PGN %d — %s\n", p.PGN, p.Description))
		b.WriteString(fmt.Sprintf("message %s {\n", msgName))
		fieldNum := 1
		for _, f := range p.Fields {
			if f.IsReserved() {
				continue
			}
			protoType := protoFieldType(f)
			comment := ""
			if f.Unit != "" {
				comment = fmt.Sprintf(" // %s", f.Unit)
			}
			b.WriteString(fmt.Sprintf("  %s %s = %d;%s\n",
				protoType, toSnake(f.Name), fieldNum, comment))
			fieldNum++
		}
		b.WriteString("}\n\n")
	}

	// Wrapper message for any PGN
	b.WriteString("// DecodedPGN wraps any decoded PGN message.\n")
	b.WriteString("message DecodedPGN {\n")
	b.WriteString("  uint32 pgn = 1;\n")
	b.WriteString("  oneof message {\n")
	fieldNum := 2
	for _, p := range s.PGNs {
		msgName := toPascal(p.Description)
		fieldName := toSnake(p.Description)
		b.WriteString(fmt.Sprintf("    %s %s = %d;\n", msgName, fieldName, fieldNum))
		fieldNum++
	}
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}

func protoFieldType(f FieldDef) string {
	if f.HasScaling() {
		return "double"
	}
	switch f.Type {
	case TypeString:
		return "string"
	case TypeFloat:
		if f.Bits == 32 {
			return "float"
		}
		return "double"
	case TypeEnum:
		return f.EnumRef
	case TypeInt:
		if f.Bits <= 32 {
			return "sint32"
		}
		return "sint64"
	default: // TypeUint
		if f.Bits <= 32 {
			return "uint32"
		}
		return "uint64"
	}
}
